
# It lets you start/stop with docker-compose up and docker-compose down.
# Your source code is shared, so changes reflect immediately.
# It compiles & runs automatically inside the container.

version: "3.8"
services:
  cpp-dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: cpp-api-dev
    volumes:
      - .:/app # Mounts local source code into the container
    working_dir: /app # Ensures we start in the correct directory
    ports:
      - "8080:8080"
    command:
      tail -f /dev/null

  # cpp-api:
  #   build:
  #     context: .
  #     dockerfile: docker/prod.Dockerfile
  #   container_name: cpp-api-prod
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - cpp-dev

  py-observability:
    build:
      context: .
      dockerfile: docker/observability.Dockerfile
    container_name: py-observability
    volumes:
      - ./observability:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command:
      tail -f /dev/null
    depends_on:
      - cpp-dev
