version: "3.8"
services:
  cpp-api:
    build: .
    container_name: cpp-api-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mounts local source code into the container
    working_dir: /app  # Ensures we start in the correct directory
    command: ["bash", "-c", "cd build && cmake .. && make -j$(nproc) && ./api_server"]

# It lets you start/stop with docker-compose up and docker-compose down.
# Your source code is shared, so changes reflect immediately.
# It compiles & runs automatically inside the container.